apiVersion: v1
kind: Service
metadata:
  name: rest-api-app-service
  labels:
    run: rest-api-app-service
spec:
  type: NodePort
  ports:
  - port: 6035
    protocol: TCP
  selector:
    app: restapi-app